sudo: required
services:
  - docker

before_install:
  - docker build -t erwandupuis/react-test -f ./client/Dockerfile.dev ./client
 
script:
  - docker run -e CI=true erwandupuis/react-test npm test

after_success:
  - docker build -t erwandupuis/multi-client ./client
  - docker build -t erwandupuis/multi-nginx ./nginx
  - docker build -t erwandupuis/multi-server ./server
  - docker build -t erwandupuis/multi-worker ./worker
  - docker login -u "erwandupuis" --password "Canada010522WithJE,;"
  - docker push erwandupuis/multi-client
  - docker push erwandupuis/multi-nginx
  - docker push erwandupuis/multi-server
  - docker push erwandupuis/multi-worker